language: shell
os:
    - linux
    - osx
    #- windows

before_install:
    # set miniconda3 path on macOS and Linux
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] || [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          export PATH="$HOME/miniconda3/bin:$PATH";
      fi

install:
    # install conda with custom script
    - bash travis/install_conda.sh

    # create and activate conda environment
    - conda env create --file environment.yml
    - source activate pytreesvg_env

script:
    # run unit test
    - python -m unittest discover -v test

    # run doctest and sphinx documentation build
    - cd doc
    - make doctest
    - make html
