name: pytreesvg_env
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - babel=2.6.0
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.4.2
  - docutils=0.14
  - idna=2.8
  - imagesize=1.1.0
  - jinja2=2.10
  - libedit=3.1.20181209
  - libffi=3.2.1
  - markupsafe=1.1.0
  - ncurses=6.1
  - openssl=1.1.1a
  - packaging=18.0
  - pip=18.1
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=18.0.0
  - pyparsing=2.3.1
  - pysocks=1.6.8
  - python=3.6.8
  - pytz=2018.9
  - readline=7.0
  - requests=2.21.0
  - setuptools=40.6.3
  - six=1.12.0
  - snowballstemmer=1.2.1
  - sphinx=1.8.2
  - sphinx_rtd_theme=0.4.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlite=3.26.0
  - tk=8.6.8
  - urllib3=1.24.1
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - future==0.16.0
    - h5py==2.7.1
    - keras==2.1.5
    - kiwisolver==1.0.1
    - matplotlib==2.2.2
    - np-utils==0.5.4.0
    - numpy==1.14.2
    - pockets==0.7.2
    - python-dateutil==2.7.2
    - scipy==1.0.1
    - seaborn==0.8.1
    - sphinxcontrib-napoleon==0.7

